import React from 'react';
import CommentList from './commentList.jsx';
import CommentForm from './commentForm.jsx';

class CommentBox extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            data: []
        };
    }

    loadCommentsFromServer() {
        fetch(this.props.url, {
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            }
        })
        .then(this.status)
        .then(this.json)
        .then(this.processData.bind(this))
        .catch(function(error) {
            console.log('Request failed', error);
        });

    }

    handleCommentSubmit(comment) {
        var comments = this.state.data;
        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        comment.id = Date.now();
        var newComments = comments.concat([comment]);
        this.setState({data: newComments});

        var formdata = JSON.stringify(comment);
        fetch(this.props.url, {
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            },
            method: 'post',
            body: formdata
        })
        .then(this.status)
        .then(this.json)
        .then(this.processData.bind(this))
        .catch(function(error) {
            console.log('Request failed', error);
        });
    }

    status(response) {
        if (response.status >= 200 && response.status < 300) {
            return Promise.resolve(response)
        } else {
            return Promise.reject(new Error(response.statusText))
        }
    }

    json(response) {
        return response.json();
    }

    processData(data) {
        this.setState({data: data});
    }

    componentDidMount() {
        this.loadCommentsFromServer();
        setInterval(this.loadCommentsFromServer(), this.props.pollInterval);
    }

    render() {
        return (
            <div className="commentBox">
                <h1>Comments</h1>
                <CommentList data={this.state.data}/>
                <CommentForm onCommentSubmit={this.handleCommentSubmit.bind(this)}/>
            </div>
        );
    }
};

export default CommentBox;
